### ISSUE TITLE
CSDN搜索问题反馈

### ISSUE THREAD

**Issue by rumingruyue** [csdntm/csdn-search#2]
1 根据关键字和作者昵称 优先搜索改作者的文章（作者可以快速搜到自己想看的，想修改的文章）

2 可以直接根据作者名搜作者（参考搜狗微信搜索，可以搜文章也可以搜公众号）

3 匹配度类似的情况下，按照作者排名，点赞数、评论数等关键指标排序。
否则前面的文章匹配度还想，但是质量不高。

4 搜索结果里可以显示，作者是不是博客专家。

5 输入时选择给出的候选词之后，居然还要再点击搜索才能搜索。

6 下面的文档太多，很碍眼。是否可以提供简洁模式，可以设置默认是否收起。

**Comment by fengbingjian** [comment]
非常感谢给我们反馈问题。
每个问题都很好，1，2，4我们很快会实现的
3是排序问题，排序是比较复杂的，不是简单的按相关度的，当然目前还是有很大优化空间，这块我们也一直在优化。敬请期待后续效果
5，6没太看明白😅，有空辛苦再给补充说明下，或者添加个截图可能更好理解
再次感谢给我们反馈问题，欢迎多提意见！

**Comment by rumingruyue** [comment]
第5条
https://so.csdn.net/search?mode=1&q=%E6%B5%8B%E8%AF%95
**在搜索首页跳转到具体搜索页面之后**（可以通过上面链接访问）
在页面左上角输入关键字，下面会有一些候选词，选择某个候选词之后，还得再点击搜索才可以自动搜索。
选择候选词之后如果不点搜索还是之前的页面。

**Comment by rumingruyue** [comment]
第6 条
https://so.csdn.net/
你们搜索首页下面各种手册，然而我使用频率并不高（比如我是Java开发，而且还不是新手，压根用不到，而且下面还有python的），强烈建议可以让用户选择是否折叠
而且手册占屏太大，看着非常不舒服，这样让我不太愿意使用这个搜索。

**Comment by rumingruyue** [comment]
> 非常感谢给我们反馈问题。
> 每个问题都很好，1，2，4我们很快会实现的
> 3是排序问题，排序是比较复杂的，不是简单的按相关度的，当然目前还是有很大优化空间，这块我们也一直在优化。敬请期待后续效果
> 5，6没太看明白😅，有空辛苦再给补充说明下，或者添加个截图可能更好理解
> 再次感谢给我们反馈问题，欢迎多提意见！
已经单独

**Comment by dhqace** [comment]
额，就是俺在输入内容后（比如计算器功能，输入123+123），然后没有出现计算结果，其他类似的都没有出现检索结果，已经连上网了
![image](https://user-images.githubusercontent.com/61268872/95984880-718d6400-0e56-11eb-944c-4ed96f41235a.png)

**Comment by liaoshengping** [comment]
请问，是否可以设置成秒级的时间戳？

比如：1603086255
